# Generated by Django 3.1.7 on 2021-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='question_to_tag', to='ask.Tag'),
        ),
    ]
