# Generated by Django 3.1.7 on 2021-03-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20210321_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='ask.Tag'),
        ),
    ]
