# Generated by Django 3.1.7 on 2021-05-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20210521_2053'),
        ('ask', '0008_auto_20210514_2113'),
    ]

    operations = [
    ]
