version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  orthodontist:
    build: ./orthodontist
    command: gunicorn orthodontist.wsgi --bind=0.0.0.0:8000
    ports:
    - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  postgres_data: