version: '3.8'

services:
  db:
    image: postgres:13.2
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  orthodontist:
    build:
      context: ./orthodontist
      dockerfile: Dockerfile.prod
    command: gunicorn orthodontist.wsgi --bind=0.0.0.0:8000
    volumes:
      - static_volume:/home/balthasar/orthodontist/static
      - media_volume:/home/balthasar/orthodontist/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  media-backup:
    image: alpine
    tty: false
    volumes:
    - ./backup:/backup
    - media_volume:/home/balthasar/orthodontist/media
    command: sh -c "tar -cjf /backup/media_volume.tar.bz2 -C /home/balthasar/orthodontist/media ./"

  media-restore:
    image: alpine
    volumes:
    - ./backup:/backup
    - media_volume:/home/balthasar/orthodontist/media
    command: sh -c "rm -rf /home/balthasar/orthodontist/media/* /home/balthasar/orthodontist/media/..?* /home/balthasar/orthodontist/media/.[!.]* ; tar -C /home/balthasar/orthodontist/media/ -xjf /backup/media_volume.tar.bz2"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/balthasar/orthodontist/static
      - media_volume:/home/balthasar/orthodontist/media
    ports:
      - 1337:80
    depends_on:
      - orthodontist

volumes:
  postgres_data:
  static_volume:
  media_volume:
