# Generated by Django 3.1.7 on 2021-03-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
