# Generated by Django 3.1.7 on 2021-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
