# Generated by Django 3.1.7 on 2021-05-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20210514_2113'),
        ('feedback', '0003_auto_20210514_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment', verbose_name='Прием'),
        ),
    ]
