# Generated by Django 3.1.7 on 2021-05-14 14:15

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20210514_2113'),
        ('feedback', '0004_auto_20210514_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment', validators=[feedback.models.validate_appointment_date], verbose_name='Прием'),
        ),
    ]
