# Generated by Django 3.1.7 on 2021-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20210514_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Электронная почта'),
        ),
    ]
