# Generated by Django 3.1.7 on 2021-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20210515_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Опубликовано'),
        ),
    ]
