# Generated by Django 3.1.7 on 2021-05-07 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название клиника')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес клиники')),
            ],
            options={
                'verbose_name': 'клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.TimeField(verbose_name='Время приема')),
                ('problem', models.CharField(default=None, max_length=1000, null=True, verbose_name='Описание проблемы')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.clinic', verbose_name='Название клиника')),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.patient')),
            ],
            options={
                'verbose_name': 'запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
    ]
