# Generated by Django 3.1.7 on 2021-05-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'клинику', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'пациента', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='problem',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Описание проблемы'),
        ),
    ]
