# Generated by Django 3.1.7 on 2021-05-08 11:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210507_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time', 'clinic'], 'verbose_name': 'запись на прием', 'verbose_name_plural': 'Записи на прием'},
        ),
        migrations.AlterModelManagers(
            name='clinic',
            managers=[
                ('clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
