# Generated by Django 3.1.7 on 2021-05-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210508_1944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clinic',
            managers=[
            ],
        ),
    ]
