# Generated by Django 3.1.7 on 2021-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20210508_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='example@tut.by', max_length=15, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='example@tut.by', max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
