# Generated by Django 3.1.7 on 2021-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20210514_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
    ]
