# Generated by Django 3.1.7 on 2021-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20210514_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time', 'clinic'], 'verbose_name': 'запись на прием', 'verbose_name_plural': 'записи на прием'},
        ),
    ]
