# Generated by Django 3.1.7 on 2021-05-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20210514_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time', 'clinic'], 'verbose_name': 'запись на прием', 'verbose_name_plural': 'записи на прием'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'клинику', 'verbose_name_plural': 'клиники'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'пациента', 'verbose_name_plural': 'пациенты'},
        ),
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона(2)'),
        ),
    ]
